//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquiposMex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPO
    {
        public EQUIPO()
        {
            this.DIRECTOR = new HashSet<DIRECTOR>();
            this.JUGADOR = new HashSet<JUGADOR>();
        }
    
        public int ID_EQUIPO { get; set; }
        public string NOMBREEQUIPO { get; set; }
        public string COLOR { get; set; }
    
        public virtual ICollection<DIRECTOR> DIRECTOR { get; set; }
        public virtual ICollection<JUGADOR> JUGADOR { get; set; }
    }
}
