//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquiposMex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JUGADOR
    {
        public int ID_JUGADOR { get; set; }
        public Nullable<int> ID_PADRE { get; set; }
        public Nullable<int> ID_EQUIPO { get; set; }
        public string NOMBREJUGADOR { get; set; }
        public string APELLIDOSJUGADOR { get; set; }
        public Nullable<int> EDAD { get; set; }
    
        public virtual EQUIPO EQUIPO { get; set; }
        public virtual PADRE PADRE { get; set; }
    }
}
