//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquiposMex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PADRE
    {
        public PADRE()
        {
            this.JUGADOR = new HashSet<JUGADOR>();
        }
    
        public int ID_PADRE { get; set; }
        public string APELLIDOSPADRE { get; set; }
        public string NOMBREPADRE { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONOPADRE { get; set; }
    
        public virtual ICollection<JUGADOR> JUGADOR { get; set; }
    }
}
